# SVG Generation from Text Prompts
DL Spring Kaggle Midterm\
Tanvir Shahriar\
ts5792

# Use of LLM Assistant
An LLM assistant (ChatGPT) was used as a development aid during this project, primarily for path handling, string manipulation, code style cleanup, sanity-check generation, and on-the-go debugging. It was also used for clarifying small implementation details, improving readability, and debugging during iterative development. All final code decisions, integration, and verification were completed by the myself.

In [14]:
import gc
import os
import re
import time
import random
from pathlib import Path
import xml.etree.ElementTree as ET

import numpy as np
import pandas as pd
import torch
from datasets import Dataset
from scipy import sparse
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
from transformers import AutoModelForCausalLM, AutoTokenizer, Trainer, TrainingArguments
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

DATA_DIR_CANDIDATES = [
    Path('/kaggle/input/dl-spring-2026-svg-generation-from-text-prompts'),
    Path('/kaggle/input/dl-spring-2026-svg-generation-from-text-prompts-extended-deadline'),
    Path('/kaggle/input'),
]
WORK_DIR = Path('/kaggle/working')
#MODEL_BASE_PATH = Path('/kaggle/input/models/qwen-lm/qwen2.5/transformers/1.5b/1')
MODEL_CANDIDATES = [
    '/kaggle/input/qwen2-5-1-5b-instruct',
    'Qwen/Qwen2.5-1.5B-Instruct',
]

CONFIG = {
    'max_seq_length': 256,
    'max_train_samples': 2000,
    'max_eval_samples': 50,
    'lora_r': 4,
    'lora_alpha': 8,
    'learning_rate': 2e-4,
    'num_train_epochs': 1,
    'per_device_train_batch_size': 1,
    'gradient_accumulation_steps': 32,
    'warmup_steps': 25,
    'weight_decay': 0.01,
    'logging_steps': 20,
    'save_steps': 0,
    'eval_steps': 0,
    'max_new_tokens': 128,
    'generation_batch_size': 1,
    'retrieval_top_k': 5,
    'output_dir': str(WORK_DIR / 'final_svg_lora_run'),
    'submission_path': str(WORK_DIR / 'submission.csv'),
}

SYSTEM_PROMPT = (
    'Generate only one compact valid SVG XML. '
    'Use width=256 height=256 viewBox="0 0 256 256". '
    'Keep under 16000 characters. '
    'Use only safe SVG tags. '
    'No markdown, no explanation, no script, no event handlers, no external references.'
)

def find_data_dir():
    seen = set()
    for root in DATA_DIR_CANDIDATES:
        if not root.exists():
            continue
        search_roots = [root]
        try:
            search_roots += [p for p in root.rglob('*') if p.is_dir()]
        except Exception:
            pass
        for candidate in search_roots:
            cand_str = str(candidate)
            if cand_str in seen:
                continue
            seen.add(cand_str)
            if (candidate / 'train.csv').exists() and (candidate / 'test.csv').exists() and (candidate / 'sample_submission.csv').exists():
                return candidate
    raise FileNotFoundError('Could not find train.csv, test.csv, and sample_submission.csv anywhere under /kaggle/input')

def looks_like_model_dir(path_obj):
    return (path_obj / 'config.json').exists() and ((path_obj / 'model.safetensors').exists() or (path_obj / 'pytorch_model.bin').exists() or (path_obj / 'model.safetensors.index.json').exists())

def find_model_name():
    for candidate in MODEL_CANDIDATES:
        try:
            p = Path(candidate)
            if p.exists() and looks_like_model_dir(p):
                return str(p)
            if p.exists():
                for sub in p.rglob('*'):
                    if sub.is_dir() and looks_like_model_dir(sub):
                        return str(sub)
        except Exception:
            pass
    input_root = Path('/kaggle/input')
    if input_root.exists():
        try:
            for sub in input_root.rglob('*'):
                 if sub.is_dir() and looks_like_model_dir(sub):
                     return str(sub)
        except Exception:
               pass
    return MODEL_CANDIDATES[-1]

def looks_like_model_dir(path_obj):
    return path_obj.is_dir() and (path_obj / 'config.json').exists() and ((path_obj / 'model.safetensors').exists() or (path_obj / 'pytorch_model.bin').exists() or (path_obj / 'model.safetensors.index.json').exists())

def resolve_model_path(base_path):
    if looks_like_model_dir(base_path):
        return str(base_path)
    if base_path.exists():
        for sub in base_path.rglob('*'):
            if looks_like_model_dir(sub):
                return str(sub)
    raise FileNotFoundError(f'Could not find a valid Transformers model directory under {base_path}')

DATA_DIR = find_data_dir()

MODEL_NAME = find_model_name()

#MODEL_NAME = resolve_model_path(MODEL_BASE_PATH)

print('Torch:', torch.__version__)
print('CUDA available:', torch.cuda.is_available())
print('Resolved DATA_DIR:', DATA_DIR)
print('Resolved MODEL_NAME:', MODEL_NAME)
CONFIG

Torch: 2.10.0+cu128
CUDA available: True
Resolved DATA_DIR: /kaggle/input/competitions/dl-spring-2026-svg-generation-from-text-prompts-extended-deadline
Resolved MODEL_NAME: /kaggle/input/models/qwen-lm/qwen2.5/transformers/1.5b/1

{'max_seq_length': 256,
 'max_train_samples': 2000,
 'max_eval_samples': 50,
 'lora_r': 4,
 'lora_alpha': 8,
 'learning_rate': 0.0002,
 'num_train_epochs': 1,
 'per_device_train_batch_size': 1,
 'gradient_accumulation_steps': 32,
 'warmup_steps': 25,
 'weight_decay': 0.01,
 'logging_steps': 20,
 'save_steps': 0,
 'eval_steps': 0,
 'max_new_tokens': 128,
 'generation_batch_size': 1,
 'retrieval_top_k': 5,
 'output_dir': '/kaggle/working/final_svg_lora_run',
 'submission_path': '/kaggle/working/submission.csv'}

In [15]:
ALLOWED_TAGS = {
    'svg','g','path','rect','circle','ellipse','line','polyline','polygon','defs','use','symbol','clipPath','mask',
    'linearGradient','radialGradient','stop','text','tspan','title','desc','style','pattern','marker','filter'
}
MAX_SVG_LEN = 16000
MAX_PATHS = 256
SVG_RE = re.compile(r'<svg[\s\S]*?</svg>', flags=re.IGNORECASE)

def local_name(tag):
    return tag.split('}')[-1]

def normalize_space(text):
    text = '' if text is None else str(text)
    text = text.replace('\n', ' ').replace('\t', ' ')
    return re.sub(r'\s+', ' ', text).strip()

def normalize_prompt(text):
    text = normalize_space(text).lower().replace('grey', 'gray')
    text = re.sub(r'[^a-z0-9\s#.,:/+\-]', ' ', text)
    return re.sub(r'\s+', ' ', text).strip()

def enforce_svg_header(svg_text):
    if not isinstance(svg_text, str):
        return ''
    svg_text = svg_text.strip()
    start = svg_text.find('<svg')
    if start >= 0:
        svg_text = svg_text[start:]
    end = svg_text.rfind('</svg>')
    if end >= 0:
        svg_text = svg_text[:end + len('</svg>')]
    return svg_text.strip()

def simple_safe_svg():
    return (
        "<svg xmlns='http://www.w3.org/2000/svg' width='256' height='256' viewBox='0 0 256 256'>"
        "<rect x='0' y='0' width='256' height='256' fill='white'/>"
        "<circle cx='128' cy='128' r='52' fill='black'/>"
        "</svg>"
    )

def svg_is_valid(svg_text):
    if not isinstance(svg_text, str):
        return False
    svg_text = enforce_svg_header(svg_text)
    if len(svg_text) == 0 or len(svg_text) > MAX_SVG_LEN:
        return False
    trimmed = svg_text.lstrip()
    if not (trimmed.startswith('<svg') or trimmed.startswith('<ns0:svg') or '<svg' in trimmed[:40]):
        return False
    try:
        root = ET.fromstring(svg_text)
    except ET.ParseError:
        return False
    if local_name(root.tag) != 'svg':
        return False
    # TS For training accept any parseable SVG viewBox/canvas.
    # TS: normalize generated outputs later.
    viewbox = root.attrib.get('viewBox')
    if viewbox is None and (root.attrib.get('width') is None or root.attrib.get('height') is None):
        return False
    path_count = 0
    for elem in root.iter():
        tag = local_name(elem.tag)
        if tag not in ALLOWED_TAGS:
            return False
        if tag == 'path':
            path_count += 1
            if path_count > MAX_PATHS:
                return False
        for attr_name, attr_val in elem.attrib.items():
            an = str(attr_name).lower()
            av = str(attr_val).lower()
            if an.startswith('on'):
                return False
            if 'javascript:' in av or 'http://' in av or 'https://' in av:
                return False
            if ('href' in an) and not str(attr_val).startswith('#') and '://' in av:
                return False
    return True

def sanitize_svg(svg_text):
    svg_text = enforce_svg_header(svg_text)
    if not svg_text or '<script' in svg_text.lower() or len(svg_text) > MAX_SVG_LEN:
        return None
    try:
        root = ET.fromstring(svg_text)
    except ET.ParseError:
        return None
    if local_name(root.tag) != 'svg':
        return None
    for elem in root.iter():
        if local_name(elem.tag) not in ALLOWED_TAGS:
            return None
        for attr_name, attr_val in list(elem.attrib.items()):
            an = str(attr_name).lower()
            av = str(attr_val).lower()
            if an.startswith('on') or 'javascript:' in av or 'http://' in av or 'https://' in av:
                return None
    root.set('xmlns', 'http://www.w3.org/2000/svg')
    root.set('width', '256')
    root.set('height', '256')
    root.set('viewBox', '0 0 256 256')
    cleaned = ET.tostring(root, encoding='unicode')
    if not svg_is_valid(cleaned):
        return None
    return cleaned

def validate_submission_svg(svg_text):
    issues = []

    if not isinstance(svg_text, str):
        issues.append('missing_svg_root_prefix')
    else:
        trimmed = str(svg_text).lstrip()
        if not (
            trimmed.startswith('<svg')
            or trimmed.startswith('<ns0:svg')
            or '<svg' in trimmed[:40]
        ):
            issues.append('missing_svg_root_prefix')

    if len(str(svg_text)) > MAX_SVG_LEN:
        issues.append('too_long')
    if '<script' in str(svg_text).lower():
        issues.append('script_tag')
    if re.search(r'on[a-zA-Z]+\s*=\s*', str(svg_text)):
        issues.append('event_handler')
    # TS: erros with parsing? check if parsing possible at all here?
    try:
        root = ET.fromstring(svg_text)
        if local_name(root.tag) != 'svg':
            issues.append('bad_root')
        if root.attrib.get('viewBox') != '0 0 256 256':
            issues.append('bad_viewBox')
        if sum(1 for el in root.iter() if local_name(el.tag) == 'path') > MAX_PATHS:
            issues.append('too_many_paths')
        for el in root.iter():
            if local_name(el.tag) not in ALLOWED_TAGS:
                issues.append('disallowed_tag')
                break
    except Exception:
        issues.append('xml_parse_error')
    return issues

In [16]:
train_df = pd.read_csv(DATA_DIR / 'train.csv')
test_df = pd.read_csv(DATA_DIR / 'test.csv')
sample_sub = pd.read_csv(DATA_DIR / 'sample_submission.csv')

# TS: insert debug here for quick checking.
DEBUG = False
DEBUG_TEST_ROWS = 50
if DEBUG:
    test_df = test_df.head(DEBUG_TEST_ROWS).copy()
    CONFIG['max_new_tokens'] = 128
    CONFIG['generation_batch_size'] = 2
    CONFIG['max_train_samples'] = min(CONFIG['max_train_samples'], 2000)
    CONFIG['max_eval_samples'] = min(CONFIG['max_eval_samples'], 100)

train_df['prompt_norm'] = train_df['prompt'].map(normalize_prompt)
test_df['prompt_norm'] = test_df['prompt'].map(normalize_prompt)

# TS: filter invalid svgs. can avoid copy()?
train_df = train_df[train_df['svg'].map(svg_is_valid)].copy()
train_df['svg_len'] = train_df['svg'].str.len()

train_df = (
    train_df.sort_values(['prompt_norm', 'svg_len'])
    .drop_duplicates('prompt_norm', keep='first')
    .reset_index(drop=True)
)

print('usable train rows:', len(train_df))
print('test rows:', len(test_df))
display(train_df[['prompt','svg_len']].head())

usable train rows: 45913
test rows: 1000

                                              prompt  svg_len
0                         饼图是一个有三个扇区的圆圈，其中一个扇区填充了颜色。      456
1                              指纹扫描技术,数码设备上安全身份的确认方式     3590
2  Σ, a symbol in the Greek alphabet, often used ...      222
3                       3D Printer creating a glass.     8758
4                         5-second refresh interval.      410

In [17]:
# TS: retrieval based on tf-idf similarity of prompts after norming, heuristics prefer more token-overlap and shorter svgs.
word_vec = TfidfVectorizer(analyzer='word', ngram_range=(1,3), min_df=2, max_df=0.98, strip_accents='unicode', sublinear_tf=True)
char_vec = TfidfVectorizer(analyzer='char_wb', ngram_range=(3,5), min_df=2, max_df=0.995, sublinear_tf=True)
Xw = word_vec.fit_transform(train_df['prompt_norm'])
Xc = char_vec.fit_transform(train_df['prompt_norm'])
X_retr = sparse.hstack([0.8 * Xw, 1.2 * Xc], format='csr')

def token_overlap(a, b):
    sa, sb = set(a.split()), set(b.split())
    return 0.0 if not sa or not sb else len(sa & sb) / len(sa | sb)

def retrieve_svg(prompt_norm):
    qw = word_vec.transform([prompt_norm])
    qc = char_vec.transform([prompt_norm])
    qx = sparse.hstack([0.8 * qw, 1.2 * qc], format='csr')
    sims = linear_kernel(qx, X_retr)[0]
    top_k = min(CONFIG['retrieval_top_k'], len(train_df))
    cand_idx = np.argpartition(-sims, kth=top_k - 1)[:top_k]
    best_j, best_score = int(cand_idx[0]), -1e18
    for j in cand_idx:
        j = int(j)
        score = float(sims[j]) + 0.08 * token_overlap(prompt_norm, train_df.iloc[j]['prompt_norm']) - 0.000005 * len(train_df.iloc[j]['svg'])
        if score > best_score:
            best_score, best_j = score, j
    return train_df.iloc[best_j]['svg']

In [18]:
# TS: stratified sampling by length, keep diversity & avoid overfitting short svgs
def stratified_length_sample(df, n_rows, seed=SEED):
    if len(df) <= n_rows:
        return df.sample(frac=1.0, random_state=seed).reset_index(drop=True)
    bins = pd.qcut(df['svg_len'], q=min(10, df['svg_len'].nunique()), duplicates='drop')
    df2 = df.assign(svg_bin=bins.astype(str))
    per_bin = max(1, n_rows // df2['svg_bin'].nunique())
    parts = []
    for _, chunk in df2.groupby('svg_bin', dropna=False):
        parts.append(chunk.sample(n=min(len(chunk), per_bin), random_state=seed))
    sampled = pd.concat(parts).drop(columns=['svg_bin'])
    if len(sampled) < n_rows:
        extra = df.drop(sampled.index, errors='ignore')
        need = min(n_rows - len(sampled), len(extra))
        if need > 0:
            sampled = pd.concat([sampled, extra.sample(n=need, random_state=seed)])
    return sampled.sample(frac=1.0, random_state=seed).head(n_rows).reset_index(drop=True)

sampled_df = stratified_length_sample(train_df, CONFIG['max_train_samples'])
eval_n = min(CONFIG['max_eval_samples'], max(20, len(sampled_df)//20))
eval_n = min(eval_n, max(1, len(sampled_df) - 50))
eval_idx = sampled_df.sample(n=eval_n, random_state=SEED).index
eval_df = sampled_df.loc[eval_idx].reset_index(drop=True)
train_fit_df = sampled_df.drop(index=eval_idx).reset_index(drop=True)

print('train rows:', len(train_fit_df))
print('eval rows:', len(eval_df))

train rows: 1950
eval rows: 50

In [19]:
# TS: quick check of retrieval quality,
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)
tokenizer.padding_side = "left"
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

MODEL_DTYPE = torch.float16 if torch.cuda.is_available() else torch.float32
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    trust_remote_code=True,
    dtype=MODEL_DTYPE,
    low_cpu_mem_usage=True,
    device_map='auto' if torch.cuda.is_available() else None,
)
model.config.use_cache = False
model.gradient_checkpointing_enable()
model = prepare_model_for_kbit_training(model)

lora_cfg = LoraConfig(
    r=CONFIG['lora_r'],
    lora_alpha=CONFIG['lora_alpha'],
    lora_dropout=0.0,
    bias='none',
    task_type='CAUSAL_LM',
    target_modules = ['q_proj', 'v_proj']
)
model = get_peft_model(model, lora_cfg)

def make_chat_text(prompt, svg):
    return (
        f'System: {SYSTEM_PROMPT}\n'
        f'User: {normalize_space(prompt)}\n'
        f'Assistant: {svg}'
    )

train_ds = Dataset.from_pandas(train_fit_df[['prompt', 'svg']], preserve_index=False)
eval_ds = Dataset.from_pandas(eval_df[['prompt', 'svg']], preserve_index=False)
train_ds = train_ds.map(lambda x: {'text': make_chat_text(x['prompt'], x['svg'])})
eval_ds = eval_ds.map(lambda x: {'text': make_chat_text(x['prompt'], x['svg'])})

def tokenize_function(batch):
    toks = tokenizer(batch['text'], max_length=CONFIG['max_seq_length'], truncation=True, padding=False)
    toks['labels'] = toks['input_ids'].copy()
    return toks

train_tok = train_ds.map(tokenize_function, batched=True, remove_columns=train_ds.column_names)
eval_tok = eval_ds.map(tokenize_function, batched=True, remove_columns=eval_ds.column_names)

def collate_fn(features):
    max_len = max(len(f['input_ids']) for f in features)
    input_ids = []
    attention_mask = []
    labels = []
    pad_id = tokenizer.pad_token_id if tokenizer.pad_token_id is not None else tokenizer.eos_token_id
    for f in features:
        ids = list(f['input_ids'])
        mask = list(f['attention_mask'])
        lab = list(f['labels'])
        pad_len = max_len - len(ids)
        input_ids.append([pad_id] * pad_len + ids)
        attention_mask.append([0] * pad_len + mask)
        labels.append([-100] * pad_len + lab)
    return {
        'input_ids': torch.tensor(input_ids, dtype=torch.long),
        'attention_mask': torch.tensor(attention_mask, dtype=torch.long),
        'labels': torch.tensor(labels, dtype=torch.long),
    }

training_args = TrainingArguments(
    output_dir=CONFIG['output_dir'],
    num_train_epochs=CONFIG['num_train_epochs'],
    per_device_train_batch_size=CONFIG['per_device_train_batch_size'],
    gradient_accumulation_steps=CONFIG['gradient_accumulation_steps'],
    learning_rate=CONFIG['learning_rate'],
    weight_decay=CONFIG['weight_decay'],
    warmup_steps=CONFIG['warmup_steps'],
    logging_steps=CONFIG['logging_steps'],
    save_strategy='no',
    eval_strategy='no',
    fp16=True,
    optim='adamw_torch',
    report_to='none',
    gradient_checkpointing=True,
    remove_unused_columns=False,
    dataloader_pin_memory=False,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tok,
    data_collator=collate_fn,
)

# TS: final training here.
train_result = trainer.train()
trainer.save_model(CONFIG['output_dir'])
tokenizer.save_pretrained(CONFIG['output_dir'])
train_result

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

Map:   0%|          | 0/1950 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/1950 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

TrainOutput(global_step=61, training_loss=1.4614819464136342, metrics={'train_runtime': 569.2953, 'train_samples_per_second': 3.425, 'train_steps_per_second': 0.107, 'total_flos': 3913826570459136.0, 'train_loss': 1.4614819464136342, 'epoch': 1.0})

In [24]:
import gc
del trainer
gc.collect()
torch.cuda.empty_cache()

# eval and generation with cache for speed.
model.eval()
model.config.use_cache = True

def extract_svg(text):
    m = SVG_RE.search(text)
    return m.group(0).strip() if m else None

def build_gen_text(prompt):
    return f'System: {SYSTEM_PROMPT}\nUser: {normalize_space(prompt)}\nAssistant: ' 

@torch.no_grad()
def generate_batch(prompts):
    texts = [build_gen_text(p) for p in prompts]
    inputs = tokenizer(texts, return_tensors='pt', padding=True, truncation=True).to(model.device)
    outputs = model.generate(
        **inputs,
        max_new_tokens=CONFIG['max_new_tokens'],
        do_sample=False,
        use_cache=True,
        pad_token_id=tokenizer.eos_token_id,
    )
    new_tokens = outputs[:, inputs['input_ids'].shape[1]:]
    decoded = tokenizer.batch_decode(new_tokens, skip_special_tokens=True)
    return [extract_svg(x) for x in decoded]

In [21]:
rows = []
stats = {'generated_valid': 0, 'fallback_retrieval': 0, 'fallback_safe_svg': 0}
t0 = time.time()
bs = CONFIG['generation_batch_size']
total = len(test_df)


# TS: infeernce here.
for start in range(0, total, bs):
    batch = test_df.iloc[start:start+bs]
    raw_svgs = generate_batch(batch['prompt'].tolist())
    for row, raw_svg in zip(batch.itertuples(index=False), raw_svgs):
        cleaned = sanitize_svg(raw_svg) if raw_svg else None
        if cleaned is not None and svg_is_valid(cleaned):
            final_svg = cleaned
            stats['generated_valid'] += 1
        else:
            retr_svg = sanitize_svg(retrieve_svg(row.prompt_norm))
            if retr_svg is not None and svg_is_valid(retr_svg):
                final_svg = retr_svg
                stats['fallback_retrieval'] += 1
            else:
                final_svg = simple_safe_svg()
                stats['fallback_safe_svg'] += 1
        rows.append({'id': row.id, 'svg': final_svg})

    done = min(start + bs, total)
    elapsed = time.time() - t0
    rate = done / elapsed if elapsed > 0 else 0
    remaining = (total - done) / rate if rate > 0 else 0
    print(f'Done {done}/{total} | elapsed {elapsed/60:.1f} min | ETA {remaining/60:.1f} min')
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

submission = pd.DataFrame(rows)
# TS: csv here.
submission.to_csv(CONFIG['submission_path'], index=False)
elapsed = (time.time() - t0) / 60
print('Saved submission:', CONFIG['submission_path'])
print('Stats:', stats)
print('Minutes:', round(elapsed, 2))
display(submission.head())

Done 1/1000 | elapsed 0.1 min | ETA 125.2 min
Done 2/1000 | elapsed 0.3 min | ETA 125.8 min
Done 3/1000 | elapsed 0.4 min | ETA 126.0 min
Done 4/1000 | elapsed 0.5 min | ETA 125.5 min
Done 5/1000 | elapsed 0.6 min | ETA 118.3 min
Done 6/1000 | elapsed 0.6 min | ETA 100.5 min
Done 7/1000 | elapsed 0.7 min | ETA 104.4 min
Done 8/1000 | elapsed 0.9 min | ETA 107.1 min
Done 9/1000 | elapsed 1.0 min | ETA 109.1 min
Done 10/1000 | elapsed 1.1 min | ETA 109.0 min
Done 11/1000 | elapsed 1.2 min | ETA 106.9 min
Done 12/1000 | elapsed 1.3 min | ETA 108.3 min
Done 13/1000 | elapsed 1.4 min | ETA 109.5 min
Done 14/1000 | elapsed 1.6 min | ETA 110.5 min
Done 15/1000 | elapsed 1.7 min | ETA 111.2 min
Done 16/1000 | elapsed 1.8 min | ETA 111.9 min
Done 17/1000 | elapsed 1.9 min | ETA 112.6 min
Done 18/1000 | elapsed 2.1 min | ETA 113.2 min
Done 19/1000 | elapsed 2.2 min | ETA 113.8 min
Done 20/1000 | elapsed 2.3 min | ETA 114.4 min
Done 21/1000 | elapsed 2.5 min | ETA 114.8 min
Done 22/1000 | elapsed 2.6 min | ETA 115.1 min
Done 23/1000 | elapsed 2.7 min | ETA 115.4 min
Done 24/1000 | elapsed 2.8 min | ETA 115.6 min
Done 25/1000 | elapsed 3.0 min | ETA 115.8 min
Done 26/1000 | elapsed 3.1 min | ETA 116.1 min
Done 27/1000 | elapsed 3.2 min | ETA 116.3 min
Done 28/1000 | elapsed 3.4 min | ETA 116.5 min
Done 29/1000 | elapsed 3.5 min | ETA 116.7 min
Done 30/1000 | elapsed 3.6 min | ETA 116.8 min
Done 31/1000 | elapsed 3.7 min | ETA 117.0 min
Done 32/1000 | elapsed 3.9 min | ETA 117.0 min
Done 33/1000 | elapsed 4.0 min | ETA 117.1 min
Done 34/1000 | elapsed 4.1 min | ETA 117.2 min
Done 35/1000 | elapsed 4.3 min | ETA 117.2 min
Done 36/1000 | elapsed 4.4 min | ETA 117.3 min
Done 37/1000 | elapsed 4.5 min | ETA 117.3 min
Done 38/1000 | elapsed 4.6 min | ETA 117.4 min
Done 39/1000 | elapsed 4.8 min | ETA 117.5 min
Done 40/1000 | elapsed 4.9 min | ETA 117.5 min
Done 41/1000 | elapsed 5.0 min | ETA 117.5 min
Done 42/1000 | elapsed 5.1 min | ETA 117.1 min
Done 43/1000 | elapsed 5.3 min | ETA 117.2 min
Done 44/1000 | elapsed 5.4 min | ETA 117.2 min
Done 45/1000 | elapsed 5.5 min | ETA 117.1 min
Done 46/1000 | elapsed 5.6 min | ETA 116.8 min
Done 47/1000 | elapsed 5.8 min | ETA 116.8 min
Done 48/1000 | elapsed 5.9 min | ETA 116.7 min
Done 49/1000 | elapsed 6.0 min | ETA 116.7 min
Done 50/1000 | elapsed 6.1 min | ETA 116.6 min
Done 51/1000 | elapsed 6.3 min | ETA 116.6 min
Done 52/1000 | elapsed 6.4 min | ETA 116.6 min
Done 53/1000 | elapsed 6.5 min | ETA 116.6 min
Done 54/1000 | elapsed 6.7 min | ETA 116.6 min
Done 55/1000 | elapsed 6.8 min | ETA 116.5 min
Done 56/1000 | elapsed 6.9 min | ETA 116.5 min
Done 57/1000 | elapsed 7.0 min | ETA 116.4 min
Done 58/1000 | elapsed 7.1 min | ETA 115.9 min
Done 59/1000 | elapsed 7.3 min | ETA 115.9 min
Done 60/1000 | elapsed 7.4 min | ETA 115.8 min
Done 61/1000 | elapsed 7.5 min | ETA 115.8 min
Done 62/1000 | elapsed 7.6 min | ETA 115.7 min
Done 63/1000 | elapsed 7.8 min | ETA 115.6 min
Done 64/1000 | elapsed 7.9 min | ETA 115.5 min
Done 65/1000 | elapsed 8.0 min | ETA 115.4 min
Done 66/1000 | elapsed 8.1 min | ETA 115.0 min
Done 67/1000 | elapsed 8.3 min | ETA 114.9 min
Done 68/1000 | elapsed 8.4 min | ETA 114.9 min
Done 69/1000 | elapsed 8.5 min | ETA 114.7 min
Done 70/1000 | elapsed 8.6 min | ETA 114.6 min
Done 71/1000 | elapsed 8.8 min | ETA 114.6 min
Done 72/1000 | elapsed 8.9 min | ETA 114.3 min
Done 73/1000 | elapsed 9.0 min | ETA 114.0 min
Done 74/1000 | elapsed 9.1 min | ETA 113.9 min
Done 75/1000 | elapsed 9.2 min | ETA 113.8 min
Done 76/1000 | elapsed 9.4 min | ETA 113.8 min
Done 77/1000 | elapsed 9.5 min | ETA 113.7 min
Done 78/1000 | elapsed 9.6 min | ETA 113.6 min
Done 79/1000 | elapsed 9.7 min | ETA 113.5 min
Done 80/1000 | elapsed 9.9 min | ETA 113.4 min
Done 81/1000 | elapsed 10.0 min | ETA 113.0 min
Done 82/1000 | elapsed 10.1 min | ETA 112.9 min
Done 83/1000 | elapsed 10.2 min | ETA 112.9 min
Done 84/1000 | elapsed 10.3 min | ETA 112.8 min
Done 85/1000 | elapsed 10.5 min | ETA 112.7 min
Done 86/1000 | elapsed 10.6 min | ETA 112.6 min
Done 87/1000 | elapsed 10.7 min | ETA 112.5 min
Done 88/1000 | elapsed 10.8 min | ETA 112.4 min
Done 89/1000 | elapsed 11.0 min | ETA 112.3 min
Done 90/1000 | elapsed 11.1 min | ETA 112.2 min
Done 91/1000 | elapsed 11.2 min | ETA 112.1 min
Done 92/1000 | elapsed 11.4 min | ETA 112.0 min
Done 93/1000 | elapsed 11.5 min | ETA 111.9 min
Done 94/1000 | elapsed 11.6 min | ETA 111.8 min
Done 95/1000 | elapsed 11.7 min | ETA 111.8 min
Done 96/1000 | elapsed 11.9 min | ETA 111.7 min
Done 97/1000 | elapsed 12.0 min | ETA 111.6 min
Done 98/1000 | elapsed 12.1 min | ETA 111.5 min
Done 99/1000 | elapsed 12.2 min | ETA 111.4 min
Done 100/1000 | elapsed 12.4 min | ETA 111.3 min
Done 101/1000 | elapsed 12.5 min | ETA 110.9 min
Done 102/1000 | elapsed 12.6 min | ETA 110.8 min
Done 103/1000 | elapsed 12.7 min | ETA 110.4 min
Done 104/1000 | elapsed 12.8 min | ETA 110.4 min
Done 105/1000 | elapsed 12.9 min | ETA 110.3 min
Done 106/1000 | elapsed 13.1 min | ETA 110.2 min
Done 107/1000 | elapsed 13.2 min | ETA 110.1 min
Done 108/1000 | elapsed 13.3 min | ETA 110.0 min
Done 109/1000 | elapsed 13.4 min | ETA 109.9 min
Done 110/1000 | elapsed 13.6 min | ETA 109.8 min
Done 111/1000 | elapsed 13.7 min | ETA 109.7 min
Done 112/1000 | elapsed 13.8 min | ETA 109.6 min
Done 113/1000 | elapsed 13.9 min | ETA 109.5 min
Done 114/1000 | elapsed 14.1 min | ETA 109.4 min
Done 115/1000 | elapsed 14.2 min | ETA 109.3 min
Done 116/1000 | elapsed 14.3 min | ETA 109.2 min
Done 117/1000 | elapsed 14.5 min | ETA 109.1 min
Done 118/1000 | elapsed 14.6 min | ETA 109.0 min
Done 119/1000 | elapsed 14.7 min | ETA 108.8 min
Done 120/1000 | elapsed 14.8 min | ETA 108.7 min
Done 121/1000 | elapsed 14.9 min | ETA 108.6 min
Done 122/1000 | elapsed 15.0 min | ETA 108.3 min
Done 123/1000 | elapsed 15.2 min | ETA 108.2 min
Done 124/1000 | elapsed 15.3 min | ETA 107.9 min
Done 125/1000 | elapsed 15.4 min | ETA 107.8 min
Done 126/1000 | elapsed 15.5 min | ETA 107.7 min
Done 127/1000 | elapsed 15.6 min | ETA 107.6 min
Done 128/1000 | elapsed 15.8 min | ETA 107.5 min
Done 129/1000 | elapsed 15.9 min | ETA 107.4 min
Done 130/1000 | elapsed 16.0 min | ETA 107.2 min
Done 131/1000 | elapsed 16.1 min | ETA 107.1 min
Done 132/1000 | elapsed 16.3 min | ETA 106.9 min
Done 133/1000 | elapsed 16.4 min | ETA 106.7 min
Done 134/1000 | elapsed 16.5 min | ETA 106.5 min
Done 135/1000 | elapsed 16.6 min | ETA 106.4 min
Done 136/1000 | elapsed 16.7 min | ETA 106.3 min
Done 137/1000 | elapsed 16.8 min | ETA 105.5 min
Done 138/1000 | elapsed 16.8 min | ETA 105.2 min
Done 139/1000 | elapsed 16.9 min | ETA 105.0 min
Done 140/1000 | elapsed 17.1 min | ETA 104.9 min
Done 141/1000 | elapsed 17.2 min | ETA 104.8 min
Done 142/1000 | elapsed 17.3 min | ETA 104.7 min
Done 143/1000 | elapsed 17.4 min | ETA 104.6 min
Done 144/1000 | elapsed 17.6 min | ETA 104.5 min
Done 145/1000 | elapsed 17.7 min | ETA 104.3 min
Done 146/1000 | elapsed 17.8 min | ETA 104.2 min
Done 147/1000 | elapsed 17.9 min | ETA 103.9 min
Done 148/1000 | elapsed 18.0 min | ETA 103.7 min
Done 149/1000 | elapsed 18.1 min | ETA 103.6 min
Done 150/1000 | elapsed 18.3 min | ETA 103.5 min
Done 151/1000 | elapsed 18.4 min | ETA 103.2 min
Done 152/1000 | elapsed 18.5 min | ETA 103.1 min
Done 153/1000 | elapsed 18.6 min | ETA 103.0 min
Done 154/1000 | elapsed 18.7 min | ETA 102.8 min
Done 155/1000 | elapsed 18.8 min | ETA 102.7 min
Done 156/1000 | elapsed 19.0 min | ETA 102.6 min
Done 157/1000 | elapsed 19.1 min | ETA 102.5 min
Done 158/1000 | elapsed 19.2 min | ETA 102.4 min
Done 159/1000 | elapsed 19.3 min | ETA 102.3 min
Done 160/1000 | elapsed 19.5 min | ETA 102.2 min
Done 161/1000 | elapsed 19.6 min | ETA 102.1 min
Done 162/1000 | elapsed 19.7 min | ETA 101.9 min
Done 163/1000 | elapsed 19.8 min | ETA 101.8 min
Done 164/1000 | elapsed 20.0 min | ETA 101.7 min
Done 165/1000 | elapsed 20.1 min | ETA 101.6 min
Done 166/1000 | elapsed 20.2 min | ETA 101.5 min
Done 167/1000 | elapsed 20.3 min | ETA 101.4 min
Done 168/1000 | elapsed 20.5 min | ETA 101.3 min
Done 169/1000 | elapsed 20.6 min | ETA 101.2 min
Done 170/1000 | elapsed 20.7 min | ETA 101.1 min
Done 171/1000 | elapsed 20.8 min | ETA 101.0 min
Done 172/1000 | elapsed 21.0 min | ETA 100.9 min
Done 173/1000 | elapsed 21.1 min | ETA 100.8 min
Done 174/1000 | elapsed 21.2 min | ETA 100.7 min
Done 175/1000 | elapsed 21.3 min | ETA 100.6 min
Done 176/1000 | elapsed 21.5 min | ETA 100.5 min
Done 177/1000 | elapsed 21.6 min | ETA 100.4 min
Done 178/1000 | elapsed 21.7 min | ETA 100.3 min
Done 179/1000 | elapsed 21.9 min | ETA 100.2 min
Done 180/1000 | elapsed 22.0 min | ETA 100.1 min
Done 181/1000 | elapsed 22.1 min | ETA 100.0 min
Done 182/1000 | elapsed 22.2 min | ETA 100.0 min
Done 183/1000 | elapsed 22.4 min | ETA 99.9 min
Done 184/1000 | elapsed 22.5 min | ETA 99.8 min
Done 185/1000 | elapsed 22.6 min | ETA 99.7 min
Done 186/1000 | elapsed 22.8 min | ETA 99.6 min
Done 187/1000 | elapsed 22.9 min | ETA 99.5 min
Done 188/1000 | elapsed 23.0 min | ETA 99.4 min
Done 189/1000 | elapsed 23.1 min | ETA 99.3 min
Done 190/1000 | elapsed 23.3 min | ETA 99.2 min
Done 191/1000 | elapsed 23.4 min | ETA 99.1 min
Done 192/1000 | elapsed 23.5 min | ETA 99.0 min
Done 193/1000 | elapsed 23.6 min | ETA 98.9 min
Done 194/1000 | elapsed 23.8 min | ETA 98.8 min
Done 195/1000 | elapsed 23.9 min | ETA 98.7 min
Done 196/1000 | elapsed 24.0 min | ETA 98.4 min
Done 197/1000 | elapsed 24.1 min | ETA 98.2 min
Done 198/1000 | elapsed 24.2 min | ETA 98.1 min
Done 199/1000 | elapsed 24.4 min | ETA 98.0 min
Done 200/1000 | elapsed 24.5 min | ETA 97.9 min
Done 201/1000 | elapsed 24.6 min | ETA 97.8 min
Done 202/1000 | elapsed 24.7 min | ETA 97.6 min
Done 203/1000 | elapsed 24.8 min | ETA 97.5 min
Done 204/1000 | elapsed 25.0 min | ETA 97.4 min
Done 205/1000 | elapsed 25.1 min | ETA 97.3 min
Done 206/1000 | elapsed 25.2 min | ETA 97.2 min
Done 207/1000 | elapsed 25.3 min | ETA 97.1 min
Done 208/1000 | elapsed 25.5 min | ETA 97.0 min
Done 209/1000 | elapsed 25.6 min | ETA 96.9 min
Done 210/1000 | elapsed 25.7 min | ETA 96.8 min
Done 211/1000 | elapsed 25.9 min | ETA 96.7 min
Done 212/1000 | elapsed 26.0 min | ETA 96.6 min
Done 213/1000 | elapsed 26.1 min | ETA 96.3 min
Done 214/1000 | elapsed 26.2 min | ETA 96.2 min
Done 215/1000 | elapsed 26.3 min | ETA 96.1 min
Done 216/1000 | elapsed 26.5 min | ETA 96.0 min
Done 217/1000 | elapsed 26.6 min | ETA 96.0 min
Done 218/1000 | elapsed 26.7 min | ETA 95.7 min
Done 219/1000 | elapsed 26.8 min | ETA 95.7 min
Done 220/1000 | elapsed 27.0 min | ETA 95.6 min
Done 221/1000 | elapsed 27.1 min | ETA 95.5 min
Done 222/1000 | elapsed 27.2 min | ETA 95.4 min
Done 223/1000 | elapsed 27.3 min | ETA 95.2 min
Done 224/1000 | elapsed 27.5 min | ETA 95.1 min
Done 225/1000 | elapsed 27.6 min | ETA 95.0 min
Done 226/1000 | elapsed 27.7 min | ETA 94.9 min
Done 227/1000 | elapsed 27.8 min | ETA 94.8 min
Done 228/1000 | elapsed 28.0 min | ETA 94.7 min
Done 229/1000 | elapsed 28.1 min | ETA 94.6 min
Done 230/1000 | elapsed 28.2 min | ETA 94.5 min
Done 231/1000 | elapsed 28.4 min | ETA 94.4 min
Done 232/1000 | elapsed 28.5 min | ETA 94.3 min
Done 233/1000 | elapsed 28.6 min | ETA 94.2 min
Done 234/1000 | elapsed 28.7 min | ETA 94.1 min
Done 235/1000 | elapsed 28.9 min | ETA 94.0 min
Done 236/1000 | elapsed 29.0 min | ETA 93.8 min
Done 237/1000 | elapsed 29.1 min | ETA 93.7 min
Done 238/1000 | elapsed 29.2 min | ETA 93.6 min
Done 239/1000 | elapsed 29.4 min | ETA 93.5 min
Done 240/1000 | elapsed 29.5 min | ETA 93.4 min
Done 241/1000 | elapsed 29.6 min | ETA 93.3 min
Done 242/1000 | elapsed 29.8 min | ETA 93.2 min
Done 243/1000 | elapsed 29.9 min | ETA 93.1 min
Done 244/1000 | elapsed 30.0 min | ETA 93.0 min
Done 245/1000 | elapsed 30.1 min | ETA 92.8 min
Done 246/1000 | elapsed 30.2 min | ETA 92.7 min
Done 247/1000 | elapsed 30.4 min | ETA 92.6 min
Done 248/1000 | elapsed 30.5 min | ETA 92.4 min
Done 249/1000 | elapsed 30.6 min | ETA 92.3 min
Done 250/1000 | elapsed 30.7 min | ETA 92.2 min
Done 251/1000 | elapsed 30.8 min | ETA 92.0 min
Done 252/1000 | elapsed 31.0 min | ETA 91.9 min
Done 253/1000 | elapsed 31.1 min | ETA 91.8 min
Done 254/1000 | elapsed 31.2 min | ETA 91.7 min
Done 255/1000 | elapsed 31.4 min | ETA 91.6 min
Done 256/1000 | elapsed 31.5 min | ETA 91.5 min
Done 257/1000 | elapsed 31.6 min | ETA 91.4 min
Done 258/1000 | elapsed 31.7 min | ETA 91.2 min
Done 259/1000 | elapsed 31.8 min | ETA 91.1 min
Done 260/1000 | elapsed 31.9 min | ETA 90.9 min
Done 261/1000 | elapsed 32.0 min | ETA 90.7 min
Done 262/1000 | elapsed 32.2 min | ETA 90.6 min
Done 263/1000 | elapsed 32.3 min | ETA 90.5 min
Done 264/1000 | elapsed 32.4 min | ETA 90.4 min
Done 265/1000 | elapsed 32.5 min | ETA 90.2 min
Done 266/1000 | elapsed 32.6 min | ETA 90.0 min
Done 267/1000 | elapsed 32.8 min | ETA 89.9 min
Done 268/1000 | elapsed 32.9 min | ETA 89.8 min
Done 269/1000 | elapsed 33.0 min | ETA 89.7 min
Done 270/1000 | elapsed 33.1 min | ETA 89.6 min
Done 271/1000 | elapsed 33.3 min | ETA 89.5 min
Done 272/1000 | elapsed 33.4 min | ETA 89.4 min
Done 273/1000 | elapsed 33.5 min | ETA 89.3 min
Done 274/1000 | elapsed 33.6 min | ETA 89.1 min
Done 275/1000 | elapsed 33.8 min | ETA 89.0 min
Done 276/1000 | elapsed 33.9 min | ETA 88.9 min
Done 277/1000 | elapsed 34.0 min | ETA 88.8 min
Done 278/1000 | elapsed 34.2 min | ETA 88.7 min
Done 279/1000 | elapsed 34.3 min | ETA 88.6 min
Done 280/1000 | elapsed 34.4 min | ETA 88.5 min
Done 281/1000 | elapsed 34.5 min | ETA 88.3 min
Done 282/1000 | elapsed 34.6 min | ETA 88.2 min
Done 283/1000 | elapsed 34.8 min | ETA 88.1 min
Done 284/1000 | elapsed 34.9 min | ETA 88.0 min
Done 285/1000 | elapsed 35.0 min | ETA 87.8 min
Done 286/1000 | elapsed 35.1 min | ETA 87.7 min
Done 287/1000 | elapsed 35.3 min | ETA 87.6 min
Done 288/1000 | elapsed 35.4 min | ETA 87.5 min
Done 289/1000 | elapsed 35.5 min | ETA 87.4 min
Done 290/1000 | elapsed 35.6 min | ETA 87.3 min
Done 291/1000 | elapsed 35.8 min | ETA 87.2 min
Done 292/1000 | elapsed 35.9 min | ETA 87.1 min
Done 293/1000 | elapsed 35.9 min | ETA 86.7 min
Done 294/1000 | elapsed 36.0 min | ETA 86.6 min
Done 295/1000 | elapsed 36.2 min | ETA 86.5 min
Done 296/1000 | elapsed 36.3 min | ETA 86.3 min
Done 297/1000 | elapsed 36.4 min | ETA 86.2 min
Done 298/1000 | elapsed 36.6 min | ETA 86.1 min
Done 299/1000 | elapsed 36.7 min | ETA 86.0 min
Done 300/1000 | elapsed 36.8 min | ETA 85.9 min
Done 301/1000 | elapsed 36.9 min | ETA 85.8 min
Done 302/1000 | elapsed 37.1 min | ETA 85.7 min
Done 303/1000 | elapsed 37.2 min | ETA 85.5 min
Done 304/1000 | elapsed 37.3 min | ETA 85.4 min
Done 305/1000 | elapsed 37.4 min | ETA 85.3 min
Done 306/1000 | elapsed 37.5 min | ETA 85.2 min
Done 307/1000 | elapsed 37.7 min | ETA 85.1 min
Done 308/1000 | elapsed 37.8 min | ETA 84.9 min
Done 309/1000 | elapsed 37.9 min | ETA 84.8 min
Done 310/1000 | elapsed 38.0 min | ETA 84.7 min
Done 311/1000 | elapsed 38.2 min | ETA 84.6 min
Done 312/1000 | elapsed 38.3 min | ETA 84.5 min
Done 313/1000 | elapsed 38.4 min | ETA 84.3 min
Done 314/1000 | elapsed 38.6 min | ETA 84.2 min
Done 315/1000 | elapsed 38.7 min | ETA 84.1 min
Done 316/1000 | elapsed 38.8 min | ETA 83.9 min
Done 317/1000 | elapsed 38.9 min | ETA 83.8 min
Done 318/1000 | elapsed 39.0 min | ETA 83.7 min
Done 319/1000 | elapsed 39.2 min | ETA 83.6 min
Done 320/1000 | elapsed 39.3 min | ETA 83.5 min
Done 321/1000 | elapsed 39.4 min | ETA 83.4 min
Done 322/1000 | elapsed 39.5 min | ETA 83.2 min
Done 323/1000 | elapsed 39.7 min | ETA 83.1 min
Done 324/1000 | elapsed 39.8 min | ETA 83.0 min
Done 325/1000 | elapsed 39.9 min | ETA 82.9 min
Done 326/1000 | elapsed 39.9 min | ETA 82.5 min
Done 327/1000 | elapsed 40.1 min | ETA 82.4 min
Done 328/1000 | elapsed 40.2 min | ETA 82.3 min
Done 329/1000 | elapsed 40.3 min | ETA 82.2 min
Done 330/1000 | elapsed 40.4 min | ETA 82.1 min
Done 331/1000 | elapsed 40.5 min | ETA 81.9 min
Done 332/1000 | elapsed 40.7 min | ETA 81.8 min
Done 333/1000 | elapsed 40.8 min | ETA 81.7 min
Done 334/1000 | elapsed 40.9 min | ETA 81.6 min
Done 335/1000 | elapsed 41.0 min | ETA 81.5 min
Done 336/1000 | elapsed 41.2 min | ETA 81.4 min
Done 337/1000 | elapsed 41.3 min | ETA 81.2 min
Done 338/1000 | elapsed 41.4 min | ETA 81.1 min
Done 339/1000 | elapsed 41.5 min | ETA 81.0 min
Done 340/1000 | elapsed 41.7 min | ETA 80.9 min
Done 341/1000 | elapsed 41.8 min | ETA 80.7 min
Done 342/1000 | elapsed 41.9 min | ETA 80.6 min
Done 343/1000 | elapsed 42.0 min | ETA 80.5 min
Done 344/1000 | elapsed 42.2 min | ETA 80.4 min
Done 345/1000 | elapsed 42.3 min | ETA 80.3 min
Done 346/1000 | elapsed 42.4 min | ETA 80.2 min
Done 347/1000 | elapsed 42.5 min | ETA 80.0 min
Done 348/1000 | elapsed 42.7 min | ETA 79.9 min
Done 349/1000 | elapsed 42.8 min | ETA 79.8 min
Done 350/1000 | elapsed 42.9 min | ETA 79.7 min
Done 351/1000 | elapsed 43.0 min | ETA 79.6 min
Done 352/1000 | elapsed 43.2 min | ETA 79.5 min
Done 353/1000 | elapsed 43.3 min | ETA 79.4 min
Done 354/1000 | elapsed 43.4 min | ETA 79.2 min
Done 355/1000 | elapsed 43.6 min | ETA 79.1 min
Done 356/1000 | elapsed 43.7 min | ETA 79.0 min
Done 357/1000 | elapsed 43.8 min | ETA 78.9 min
Done 358/1000 | elapsed 43.9 min | ETA 78.8 min
Done 359/1000 | elapsed 44.0 min | ETA 78.6 min
Done 360/1000 | elapsed 44.2 min | ETA 78.5 min
Done 361/1000 | elapsed 44.3 min | ETA 78.4 min
Done 362/1000 | elapsed 44.4 min | ETA 78.3 min
Done 363/1000 | elapsed 44.5 min | ETA 78.2 min
Done 364/1000 | elapsed 44.7 min | ETA 78.1 min
Done 365/1000 | elapsed 44.8 min | ETA 77.9 min
Done 366/1000 | elapsed 44.9 min | ETA 77.8 min
Done 367/1000 | elapsed 45.1 min | ETA 77.7 min
Done 368/1000 | elapsed 45.2 min | ETA 77.6 min
Done 369/1000 | elapsed 45.3 min | ETA 77.5 min
Done 370/1000 | elapsed 45.4 min | ETA 77.4 min
Done 371/1000 | elapsed 45.6 min | ETA 77.2 min
Done 372/1000 | elapsed 45.7 min | ETA 77.1 min
Done 373/1000 | elapsed 45.8 min | ETA 77.0 min
Done 374/1000 | elapsed 45.9 min | ETA 76.9 min
Done 375/1000 | elapsed 46.1 min | ETA 76.8 min
Done 376/1000 | elapsed 46.2 min | ETA 76.7 min
Done 377/1000 | elapsed 46.3 min | ETA 76.5 min
Done 378/1000 | elapsed 46.4 min | ETA 76.4 min
Done 379/1000 | elapsed 46.6 min | ETA 76.3 min
Done 380/1000 | elapsed 46.7 min | ETA 76.2 min
Done 381/1000 | elapsed 46.8 min | ETA 76.1 min
Done 382/1000 | elapsed 46.9 min | ETA 75.9 min
Done 383/1000 | elapsed 47.1 min | ETA 75.8 min
Done 384/1000 | elapsed 47.2 min | ETA 75.7 min
Done 385/1000 | elapsed 47.3 min | ETA 75.6 min
Done 386/1000 | elapsed 47.5 min | ETA 75.5 min
Done 387/1000 | elapsed 47.6 min | ETA 75.4 min
Done 388/1000 | elapsed 47.7 min | ETA 75.2 min
Done 389/1000 | elapsed 47.8 min | ETA 75.1 min
Done 390/1000 | elapsed 48.0 min | ETA 75.0 min
Done 391/1000 | elapsed 48.1 min | ETA 74.9 min
Done 392/1000 | elapsed 48.2 min | ETA 74.7 min
Done 393/1000 | elapsed 48.3 min | ETA 74.6 min
Done 394/1000 | elapsed 48.4 min | ETA 74.5 min
Done 395/1000 | elapsed 48.6 min | ETA 74.4 min
Done 396/1000 | elapsed 48.7 min | ETA 74.3 min
Done 397/1000 | elapsed 48.8 min | ETA 74.1 min
Done 398/1000 | elapsed 48.9 min | ETA 74.0 min
Done 399/1000 | elapsed 49.1 min | ETA 73.9 min
Done 400/1000 | elapsed 49.2 min | ETA 73.8 min
Done 401/1000 | elapsed 49.3 min | ETA 73.7 min
Done 402/1000 | elapsed 49.4 min | ETA 73.5 min
Done 403/1000 | elapsed 49.6 min | ETA 73.4 min
Done 404/1000 | elapsed 49.7 min | ETA 73.3 min
Done 405/1000 | elapsed 49.8 min | ETA 73.2 min
Done 406/1000 | elapsed 49.9 min | ETA 73.1 min
Done 407/1000 | elapsed 50.1 min | ETA 72.9 min
Done 408/1000 | elapsed 50.2 min | ETA 72.8 min
Done 409/1000 | elapsed 50.3 min | ETA 72.7 min
Done 410/1000 | elapsed 50.4 min | ETA 72.6 min
Done 411/1000 | elapsed 50.6 min | ETA 72.4 min
Done 412/1000 | elapsed 50.7 min | ETA 72.3 min
Done 413/1000 | elapsed 50.8 min | ETA 72.2 min
Done 414/1000 | elapsed 50.9 min | ETA 72.1 min
Done 415/1000 | elapsed 51.1 min | ETA 72.0 min
Done 416/1000 | elapsed 51.2 min | ETA 71.9 min

,id,svg
0,fa1d8fa7-080f-4269-a9cf-a17562c9a0ca,"<ns0:svg xmlns:ns0=""http://www.w3.org/2000/svg..."
1,6eede943219547c22ac56085027d33cc,"<ns0:svg xmlns:ns0=""http://www.w3.org/2000/svg..."
2,ea045c7a247166f061ce504d9b7ccaab,"<ns0:svg xmlns:ns0=""http://www.w3.org/2000/svg..."
3,8fe82f3af89e487b31236ca829c3f071,"<ns0:svg xmlns:ns0=""http://www.w3.org/2000/svg..."
4,600464e4d92c75338462271a09b3f176,"<ns0:svg xmlns:ns0=""http://www.w3.org/2000/svg..."

In [22]:
# final checks.
validation_issues = submission['svg'].map(validate_submission_svg)
bad_rows = int((validation_issues.map(len) > 0).sum())
print('rows with validation issues:', bad_rows)
if bad_rows:
    display(submission.loc[validation_issues.map(len) > 0].assign(issues=validation_issues[validation_issues.map(len) > 0]).head())
else:
    print('All submission rows passed local validation checks.')

rows with validation issues: 0
All submission rows passed local validation checks.